spring:
  mvc:
    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true

#  resources:
#    static-locations: classpath:/haha/


server:
  servlet:
    context-path: /world